services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prova
    ports:
      - 3306:3306